### ISSUE TITLE
lgamma is deprecated to logabsgamma

### ISSUE THREAD

**Issue by aminya** [JuliaMath/IntelVectorMath.jl#20]
<del> In the Julia 1 branch (https://github.com/JuliaMath/VML.jl/pull/17) or once it is merged, </del> 
we should address this. 

https://github.com/JuliaMath/SpecialFunctions.jl/blob/master/src/deprecated.jl#L1

**Comment by Crown421** [comment]
I am not sure how we would do that?
The function that VML provides is lgamma and I don't see nice way and a good reason to force some VML.logabsgamma(a)[1] syntax. 
What should be changed is the use of `Base.lgamma` in the tests, which might require special treatment.

**Comment by aminya** [comment]
Maybe we can just wrap VML.lgamma in some function.

**Comment by Crown421** [comment]
The deprecation warnings in tests have been removed in #60 . I don't see further need for changes here, as we can continue to have `IVM.lgamma`
