### ISSUE TITLE
More comprehensive benchmark

### ISSUE THREAD

**Issue by aminya** [JuliaMath/IntelVectorMath.jl#25]
Work is in progress in https://github.com/aminya/AcuteBenchmark.jl

**Comment by Crown421** [comment]
This might be relevant here:
https://discourse.julialang.org/t/repeated-benchmark-causes-ram-creep/31533/5

**Comment by aminya** [comment]
That is strange, I didn't have any issues. I have 8GB of RAM on Windows 10.

**Comment by Crown421** [comment]
How many have you been running in a given session?

**Comment by aminya** [comment]
In https://github.com/juliamatlab/Julia-Matlab-Benchmark I used 17 function*23 size* running each 4 times!

**Comment by aminya** [comment]
AcuteBenchmark is almost ready.
https://github.com/aminya/AcuteBenchmark.jl

I will change to that for VML.jl some time this week

**Comment by Crown421** [comment]
What we should also do is test this against Yeppp and AppleAccelerate. From my personal experience VML is superior to both, but it would be nice to quantify that.
