### ISSUE TITLE
Change Repo Name to IntelVectorMath

### ISSUE THREAD

**Issue by Crown421** [JuliaMath/IntelVectorMath.jl#29]
Following discussions in https://github.com/JuliaRegistries/General/pull/5942, the name of this package was changed to `IntelVectorMath`.

Now we need a repo admin to change the name of this repo to reflect this. 

@ViralBShah

**Comment by simonbyrne** [comment]
Done

**Comment by Crown421** [comment]
Many thanks!

**Comment by simonbyrne** [comment]
Thanks for taking this repo over! It really needed some love.

**Comment by ViralBShah** [comment]
Second that.
