### ISSUE TITLE
Is Julia 32 bit faster than Julia 64 bit?

### ISSUE THREAD

**Issue by Sinansi** [JuliaMath/IntelVectorMath.jl#47]
Sir, I have a question about the performance charts on your webpage:

https://github.com/JuliaMath/IntelVectorMath.jl#performance

Is Julia 32 bit faster than Julia 64 bit?

I see huge difference between them! And 32 is winning in most cases.

I am using Windows 10 x64 bit and installed Julia x64 bit.

Should I use Julia 32 bit instead?

Thank you!

**Comment by KristofferC** [comment]
The 32-bit vs 64-bit Julia builds is for integers. The benchmarks posted are for floating point numbers. You should keep using the 64-bit Julia.

**Comment by Sinansi** [comment]
@KristofferC Thank you so much!
